name: pwlp
description: A new Flutter application.
version: 1.0.5 #+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5

  rflutter_alert:

  toast:
  dio:
  url_launcher: ^6.1.5

  percent_indicator:
  http:

  flutter_progress_hud:
  shared_preferences: any
  provider: any
  cached_network_image:
  image_picker: ^0.8.5+3
  date_format:
  flutter_offline:
  flutter_barcode_scanner: ^2.0.0
  path: ^1.8.1
  crypto: ^3.0.2
  device_info_plus: ^8.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:

  uses-material-design: true

  assets:
    - Assets/

  fonts:
    - family: texgyreadventor
      fonts:
        - asset: CustomFont/texgyreadventor-bold.ttf
        - asset: CustomFont/texgyreadventor-bolditalic.ttf
        - asset: CustomFont/texgyreadventor-italic.ttf
        - asset: CustomFont/texgyreadventor-regular.ttf
        - asset: CustomFont/GARA.ttf

      #  style: italic

    - family: Garamond
      fonts:
        - asset: CustomFont/Garamond.ttf

